### ISSUE TITLE
Deadlock possible with new allocator

### ISSUE THREAD

**Issue by f-bro** [embed-rs/stm32f7-discovery#40]
The new allocator uses a spin-lock to synchronize the access to the `ALLOCATOR`(LockedHeap).

Following sequence can result in a deadlock:

1. `ISR1` is entering the lock.
2. `ISR1` is preempted. `ISR2` has higher priority and tries to access the lock. Scine the lock is already entered by `ISR1`, `ISR2` has to wait in a loop until `ISR1` has left the lock.

`ISR1` and `ISR2` don't make progress => Deadlock

**Solution**: Use the PRIMASK register on cortex m processors to synchronize the critical section by disabling interrutps.

See pull request for `CortexMHeap` https://github.com/japaric/alloc-cortex-m/pull/6

**Comment by phil-opp** [comment]
`LockedHeap` is a wrapper type around `Heap` that uses a spinlock to [implement the `Alloc` trait for shared references](https://github.com/phil-opp/linked-list-allocator/blob/master/src/lib.rs#L166-L174) (`&LockedHeap`). This is required to be able to use it as a global allocator (see the [RFC](https://github.com/rust-lang/rfcs/blob/master/text/1974-global-allocators.md#defining-an-allocator)).

Instead of `LockedHeap`, we should create another wrapper type around `Heap` that uses the PRIMASK register instead of a spinlock. This wrapper type could live in either this crate or directly in linked-list-allocator.

I'm on vacation for the next four weeks, but I will look into this afterwards. It should be straightforward to implement such a wrapper type though (it should be pretty similar to the [implementation of `LockedHeap`](https://github.com/phil-opp/linked-list-allocator/blob/master/src/lib.rs#L166-L174), but with a PRIMASK Mutex instead of a spinlock Mutex).

**Comment by f-bro** [comment]
I have already implemented a wrapper (`CortexMHeap`) and sent a PR to the alloc-cortex-m repo. I just wait until it is merged. When it is merged, I will switch the `ALLOCATOR` to the new `CortexMHeap`.

Enjoy your vacation :)

**Comment by phil-opp** [comment]
Perfect, thanks!
